server:
  port: 5555

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres_password
  data:
    redis:
      host: redis
      port: 6379
      password: redis_password
    mongodb:
      host: mongo
      port: 27017
      authentication-database: bkguidance
      database: bkguidance
      username: mongodb
      password: mongo_password
  rabbitmq:
    host: rabbit
    port: 5672
    username: rabbit
    password: rabbit_password
    virtual-host: /
  jpa:
    show-sql: true
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      mode: always
      continue-on-error: false