insert into users values
(1, "Mary", 18, "test@test.com"),
(2, "Tom", 10, "admin@example.com"),
(3, "judy", 10, "test@test.com"),
(4, "ruby", 10, "test@test.com"),
(5, "jenny", 10, "test@test.com"),
(6, "jonney", 10, "test@test.com"),
(7, "thompson", 10, "test@test.com"),
(8, "jason", 10, "test@test.com"),
(9, "merry", 10, "test@test.com"),
(10, "jerry", 10, "test@test.com");