/*
 * This file is generated by jOOQ.
 */
package com.szuse.bkguidance.jooq;

import com.szuse.bkguidance.jooq.tables.User;
import com.szuse.bkguidance.jooq.tables.records.UserRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/** A class modelling foreign key relationships and constraints of tables in public. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

  // -------------------------------------------------------------------------
  // UNIQUE and PRIMARY KEY definitions
  // -------------------------------------------------------------------------

  public static final UniqueKey<UserRecord> USER_EMAIL_KEY =
      Internal.createUniqueKey(
          User.USER, DSL.name("user_email_key"), new TableField[] {User.USER.EMAIL}, true);
  public static final UniqueKey<UserRecord> USER_PKEY =
      Internal.createUniqueKey(
          User.USER, DSL.name("user_pkey"), new TableField[] {User.USER.ID}, true);
}
