/*
 * This file is generated by jOOQ.
 */
package com.szuse.bkguidance.jooq.tables.interfaces;

import java.time.LocalDate;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public interface IUser {

  /** Getter for <code>public.user.id</code>. userId */
  public Long getId();

  /** Setter for <code>public.user.id</code>. userId */
  public void setId(Long value);

  /** Getter for <code>public.user.email</code>. email */
  public String getEmail();

  /** Setter for <code>public.user.email</code>. email */
  public void setEmail(String value);

  /** Getter for <code>public.user.username</code>. username */
  public String getUsername();

  /** Setter for <code>public.user.username</code>. username */
  public void setUsername(String value);

  /** Getter for <code>public.user.account</code>. account */
  public String getAccount();

  /** Setter for <code>public.user.account</code>. account */
  public void setAccount(String value);

  /** Getter for <code>public.user.password</code>. password */
  public String getPassword();

  /** Setter for <code>public.user.password</code>. password */
  public void setPassword(String value);

  /** Getter for <code>public.user.avatar</code>. avatar */
  public String getAvatar();

  /** Setter for <code>public.user.avatar</code>. avatar */
  public void setAvatar(String value);

  /** Getter for <code>public.user.create_time</code>. create_time */
  public LocalDate getCreateTime();

  /** Setter for <code>public.user.create_time</code>. create_time */
  public void setCreateTime(LocalDate value);

  /** Getter for <code>public.user.update_time</code>. update_time */
  public LocalDate getUpdateTime();

  /** Setter for <code>public.user.update_time</code>. update_time */
  public void setUpdateTime(LocalDate value);

  /** Getter for <code>public.user.deleted</code>. deleted */
  public Boolean getDeleted();

  /** Setter for <code>public.user.deleted</code>. deleted */
  public void setDeleted(Boolean value);

  // -------------------------------------------------------------------------
  // FROM and INTO
  // -------------------------------------------------------------------------

  /** Load data from another generated Record/POJO implementing the common interface IUser */
  public void from(IUser from);

  /** Copy data into another generated Record/POJO implementing the common interface IUser */
  public <E extends IUser> E into(E into);
}
